config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :activities
  devise_for :users
  resources :movies do
    resources :reviews, except: [:destroy]
  end
  resources :categories do
    resources :movies, only: [:index], controller: 'categories_movies'
  end
  root "movies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :user
  belongs_to :category
  has_many   :reviews, dependent: :destroy
  
  validates :title, length: { maximum: 45,
             too_long: "%{count} characters is the maximum allowed" }, presence: true
  validates :description, length: { maximum: 200,
             too_long: "%{count} characters is the maximum allowed" }, presence: true
  validates :director, length: { maximum: 50,
             too_long: "%{count} characters is the maximum allowed" }, presence: true
  validates :movie_length, length: { maximum: 250,
             too_long: "%{count} is the maximum allowed" }, presence: true
  
  validates_numericality_of :movie_length, greater_than_or_equal_to: 0
  has_attached_file :image, styles: { medium: "250x350#", large: "325x475#" }
  validates :image, attachment_presence: true
  validates_with AttachmentSizeValidator, attributes: :image, less_than: 1.megabytes
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
  include PublicActivity::Common
  # tracked owner: ->(controller, model) { controller && controller.current_user }
  
  belongs_to :movie
  belongs_to :user

  validates :comment, presence: true
  validates :rating, :inclusion => 0..10
end

app/models/user.rb
class User < ApplicationRecord
  has_many :movies
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @activities = Activities.new.call(current_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include PublicActivity::StoreController

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_movies_controller.rb
class CategoriesMoviesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @movies = Movie.where(category_id: @category.id).order("created_at DESC")
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    @movies = Movie.all.order("created_at DESC")
  end

  def show
    if @movie.reviews.blank?
      @average_review = 0
    else
      @average_review = @movie.reviews.average(:rating).round(2)
    end
  end

  def new
    @movie = current_user.movies.build
  end

  def create
    if CreateMovieService.new.call(movie_params, current_user)
      redirect_to root_path
    else
      render 'movies/new'
    end
  end

  def edit
    @movie_categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @movie.category_id = params[:category_id]
    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render 'edit'
    end
  end

  def destroy
    @movie.destroy
    redirect_to root_path
  end

  private
    def movie_params
      params.require(:movie).permit(:title, :description,
            :movie_length, :director, :image, :category_id)
    end

    def find_movie
      @movie = Movie.find(params[:id])
    end
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_movie
  before_action :find_review, only: [:edit, :update]
  before_action :authenticate_user!, only: [:new, :edit]
   
  def new
    @review = Review.new
  end

  def create
    if @review = CreateReviewService.new.call(params[:movie_id], review_params, current_user)
      @review.create_activity :create, owner: current_user
      redirect_to movie_path(@movie)
    else
      render 'new'
    end
  end
 
  def edit
  end
 
  def update
    if @review.update(review_params)
      redirect_to movie_path(@movie)
    else
      render 'new'
    end
  end
 
  private
    def review_params
      params.require(:review).permit(:rating, :comment)   
    end
 
    def find_movie
      @movie = Movie.find(params[:movie_id])
    end
 
    def find_review
      @review = current_user.reviews.find(params[:id]) || render_404
    end
 
    def render_404
      rescue ActiveRecord::RecordNotFound
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Film Rating App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/views/activities/index.html.erb
<h1>Recent Activities</h1>

<% @activities.each do |activity| %>
  <div class="activity">
    <% if activity.owner.name.nil? %>
      <%= link_to "Unknown", '#' %>
    <% else %>
      <%= link_to activity.owner.name, '#' %>
    <% end %>
    <%= render_activity activity %>
  </div>
<% end %>

app/views/categories_movies/index.html.erb
<% provide(:title, "Films") %>

<h1 class="current-category"><%= params[:category] %></h1>
<% if @movies.count == 0 %>
  <h1>There are no movies currently in this category</h1>
<% else %>
<div class="row">
  <% @movies.each do |movie| %>
  <div class="col-md-3">
    <%= link_to image_tag(movie.image.url(:medium), class: "movie"), movie, class: "movie-index" %>
  </div>
  <% end %>
</di>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Movie Review", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>      
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Recent Activities<span class="caret"></span></a>
            <ul class="dropdown-menu" id="activity-box" role="menu">
            <% PublicActivity::Activity.last(4).each do |activity| %>
              <li>
                <%= activity.owner.name %>
                <%= render_activity activity %>
              </li>
            <% end %>
            <li><b><%= link_to "see all...", activities_path %></b></li>
          </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name %>">
                  <%= link_to category.name, category_movies_path(category), class: "link" %>
                </li>
              <% end %>
            </ul>
          </li>
          <li><%= link_to "Add Movie", new_movie_path %></li>
        </ul>
      </div>
    </nav>
    <div class="container">
       <div class="row">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie, :html => { :multipart => true } do |f| %>
  <%= f.error_notification %>
  <%= f.association  :category, :prompt => "Select a category" %>
  <%= f.input  :title, label: "Movie title" %>
  <%= f.input  :description %>
  <%= f.input  :director %>
  <%= f.input  :movie_length %>
  <%= f.input  :image %>
  <%= f.button :submit, class: "btn-custom2" %>
  <%= link_to "Cancel", root_path, class: "btn btn-default btn-custom2" %>
<% end %>

app/views/movies/edit.html.erb
<% provide(:title, 'Edit Film') %>

<div class="col-md-6 col-md-offset-3">
  <div class="edit-movie-form">
    <h1>Edit Movie</h1>
    <%= simple_form_for @movie, :html => { :multipart => true } do |f| %>
      <%= f.select :category_id, @movie_categories %>
      <%= f.input  :title, label: "Movie title" %>
      <%= f.input  :description %>
      <%= f.input  :director %>
      <%= f.input  :movie_length %>
      <%= f.input  :image %>
      <%= f.button :submit, class: "btn-custom2" %>
      <%= link_to "Cancel", movie_path(@movie), class: "btn btn-default btn-custom2" %>
    <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<% provide(:title, "Films") %>

<div class="row">
  <% @movies.each do |movie| %>
  <div class="col-md-3">
    <%= link_to image_tag(movie.image.url(:medium), class: "movie"), movie, class: "movie-index" %>
  </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<% provide(:title, 'Add Film') %>

<div class="col-md-6 col-md-offset-3">
  <div class="new-movie-form">
    <h1>New Movie</h1>
    <%= render '/movies/form' %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @movie.image.url(:large), class: "movie-show" %>
  </div>
  <div class="col-md-8">
    <div class="movie-info">
      <h2 class="movie-title"><%= @movie.title %></h2>
      <h3 class=movie-director><span>Directed by: </span><%= @movie.director %></h3>
      <h3 class=movie-director><span>Duration: </span><%= @movie.movie_length %> minutes</h3>
      <h2 class="avg-rating">Average Rating</h2>
      <div class="average-review-rating" data-score=<%= @average_review %>></div>
      <span>Based on <%= @movie.reviews.count %> reviews</span>
      <p class="movie-desc"><%= @movie.description %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="reviews">
      <h1>Reviews</h1>
      <%= render @movie.reviews %>
      <div>
        <%= link_to "Add Review", new_movie_review_path(@movie), class: "btn-custom" %>
      </div>
    </div>
  </div>
</div>
<div class="links btn-group">
  <% if user_signed_in? %>
    <% if @movie.user_id == current_user.id %>
      <%= link_to "Edit", edit_movie_path(@movie), class: "btn btn-custom" %>
      <%= link_to "Delete", movie_path(@movie), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-custom" %>
    <% end %>
  <% end %>

  <%= link_to "Back", root_path, class: "btn btn-custom" %>
</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/images/ratyrate',
    number: 10
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/images/ratyrate',
    score: function() {
      return $(this).attr('data-score');
    },
    number: 10
  });
</script>

app/views/public_activity/movie/_create.html.erb
added a movie

<% if activity.trackable %>
  <%= link_to activity.trackable.title, activity.trackable %>
<% else %>
  which has since been removed
<% end %>

app/views/public_activity/movie/_destroy.html.erb
removed a movie

app/views/public_activity/movie/_update.html.erb
updated movie

<% if activity.trackable %>
  <%= link_to activity.trackable.title, activity.trackable %>
<% else %>
  which has since been removed
<% end %>

app/views/public_activity/review/_create.html.erb
added a review

<% if activity.trackable %>
  to <%= link_to activity.trackable.movie.title, activity.trackable.movie %>
<% else %>
  which has since been removed
<% end %>

app/views/public_activity/review/_destroy.html.erb
removed a review

app/views/public_activity/review/_update.html.erb
updated review

<% if activity.trackable %>
  on <%= link_to activity.trackable.movie.name, activity.trackable.movie %>
<% else %>
  which has since been removed
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for([@movie, @review]) do |f| %>
  <%= f.error_notification %>
  <div id="rating-form">
    <label>Rating</label>
    <%= f.error :rating %>
  </div>
  <%= f.input  :comment %>
  <%= f.button :submit, class: "btn-custom2" %>
  <%= link_to "Cancel", movie_path(@movie), class: "btn btn-default btn-custom2" %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/images/ratyrate',
    scoreName: 'review[rating]',
    number: 10,
    cancel: true
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating" data-score="<%= review.rating %>"></div>
  <p class="review-comment"><%= review.comment %></p>
  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div class="links btn-group">
        <%= link_to "Edit", edit_movie_review_path(review.movie, review), class: "btn btn-custom" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<% provide(:title, 'Edit Review') %>

<div class="col-md-6 col-md-offset-3">
  <div class="edit-review-form">
    <h1>Edit Review</h1>
    <%= simple_form_for([@movie, @review]) do |f| %>
      <div id="rating-form">
        <label>Rating</label>
      </div>
      <%= f.input  :comment %>
      <%= f.button :submit, class: "btn-custom2" %>
      <%= link_to "Cancel", movie_path(@movie), class: "btn btn-default btn-custom2" %>
    <% end %>
  </div>
</div>

<script>
  $('#rating-form').raty({
    path: '/images/ratyrate',
    scoreName: 'review[rating]',
    number: 10,
    score: <%= @review.rating %>,
    cancel: true
  });
</script>

app/views/reviews/new.html.erb
<% provide(:title, 'Add Review') %>

<div class="col-md-6 col-md-offset-3">
  <div class="new-review-form">
    <h1>New Review</h1>
    <%= render 'form' %>
  </div>
</div>